source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
  pod 'PBJVision'
  pod 'GPUImage'
  pod 'AviarySDK'
  pod 'TTTAttributedLabel'
  pod 'PureLayout'
  pod 'KZPropertyMapper'
  pod 'MHPrettyDate'
  pod 'UALogger'
  pod 'AFNetworking'