#!/bin/sh

# Generate file GeneratedGitInfo.h, which defines several constants reflecting the git state for the current build.
# Another way to do this is to set CFBundleVersions with "defaults write", but it is less versatile and always
# one build behind.

# The generated info is displayed for Debug builds in the About screen (SVSettingsAboutViewController.m)

kShortSHA=`git rev-parse --short HEAD`

kCurrentBranch=`git rev-parse --abbrev-ref HEAD`

# A bit verbose, but doesn't fail for missing remotes
kRemoteTracking=`git for-each-ref --format='%(upstream:short)' $(git symbolic-ref -q HEAD)`

kBuildTime=`date "+%d-%b %H:%M:%S"`

git diff --quiet
if [ $? -ne 0 ]; then
    kIsDirty=YES
else
    kIsDirty=NO
fi

echo "//
//  GeneratedGitInfo.h
//
//  GENERATED FILE, DO NOT EDIT!!
//
//  Git info constants, generated by tools/genGitInfo.sh
//

#define kShortSHA @\"${kShortSHA}\"
#define kCurrentBranch @\"${kCurrentBranch}\"
#define kRemoteTracking @\"${kRemoteTracking}\"
#define kBuildTime @\"${kBuildTime}\"
#define kIsDirty ${kIsDirty}
" > $PROJECT_DIR/shotvibe/GeneratedGitInfo.h

